# Generated by Django 5.2.9 on 2026-01-07 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=40)),
                ('tech', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to='images/')),
                ('doc', models.FileField(upload_to='documents/')),
            ],
            options={
                'db_table': 'ProfilesInfo',
            },
        ),
    ]
